version: '3.7'

services:
  onmt:
    build: ./server-docker
    volumes:
      - "./onmt/available_models:/onmt/available_models"
    restart: always

  
networks:
  nginx-bridge:
    external: true
